### ISSUE TITLE
Using a mentoring callsign in TeamSpeak

### ISSUE THREAD

**Issue by atoff** [VATSIM-UK/core#1015]
Currently due to the restirctions of the process ATC script [here](https://github.com/VATSIM-UK/core/blob/development/app/Console/Commands/NetworkData/ProcessNetworkData.php), members are unable to use their mentoring callsign as part of the TeamSpeak callsign-appending system.

Should we look to add this?

**Comment by NFarrington** [comment]
Would there be any advantage for mentors using their callsign on TeamSpeak? Normally, all coordination would be done through the active controller (student), and the mentor is simply observing relatively unnoticed.

If we did want to implement this, the easiest way would probably be to create sessions with frequencies outside the accepted range, and then delete them when they disconnect or set a frequency (since we don't want to actually log the sessions).

**Comment by atoff** [comment]
I agree that the mentor does not really need their callsign reflected in TeamSpeak, and the code changes to accommodate this would likely not be worth it. Although I do see that in some circumstances it might be beneficial? (Namely, when both the mentee and mentor enter a room for coordination, it is clear why the mentor is there, or if someone on TeamSpeak wanted to coordinate a certain scenario to test the student etc)

This is the same as how we currently don't record OBS sessions because there is nothing really to be gained from appending an observing callsign on TeamSpeak, or the data generated - just using update space.

**Comment by CalumTowers** [comment]
I think we are running a risk of providing a solution to a problem that doesn't exist a little. The percentage of controllers that put the callsign in their name and take advantage of this feature is small. An equally small percentage of mentors would see very few using any changes we make.

**Comment by atoff** [comment]
Closing due to reasons listed above.
