### ISSUE TITLE
V/T reference token expiring, but not reference

### ISSUE THREAD

**Issue by atoff** [VATSIM-UK/core#1023]
When the reference token expires (14 days after the reference is created), it leaves the reference without a token, therefore it means that the referee will get an error the next time they go to their V/T dashboard or try to do the reference after this time(unless the application is deleted in time). 

Therefore, we need to allow references to expire, and when they do force the applicant to add another reference.

**Comment by atoff** [comment]
confirgure https://github.com/VATSIM-UK/core/blob/development/app/Console/Commands/VisitTransfer/ApplicationsCleanup.php to:​
- Find V/T applications that have expired references​ (add a new column expires_at and check that the reference status is still 30?)
- Delete the reference and its token, and send a notification to the user to add a new reference?​

or make the reference token not expire?

**Comment by NFarrington** [comment]
Have we checked with Community whether they actually require a time limit for completing references? It seems like it might make more sense for an application, that is awaiting references to be completed, to have the time limit, rather than the reference itself.

It would also be much easier to simply allow the token to never expire.

Ultimately, dependent on what CERT2 brings us, if we still need to make changes we will move away from using the tokens in the first place - tokens are only ever useful when a user isn't authenticated (e.g. for a password reset). If they're authenticated, then that's how we should be validating their access and listing what references they need to complete.
