### ISSUE TITLE
Password Reset

### ISSUE THREAD

**Issue by CalumTowers** [VATSIM-UK/core#1077]
On an individual member's page, we should be able to

- Trigger a password email
- Disable a secondary password

Both of these should be individually controlled via a permission.

When disabling a secondary password, the admin should specify a reason and the user should be notified that this has been done and be given the reason.The reason should be logged.

**Comment by NFarrington** [comment]
What sort of situation might this be required in?

All users should be able to disable their own secondary password (if they are not staff). If they cannot remember it, they should use reset form to reset their password.

Similarly, all users should be able to reset their own passwords through the application using the link provided. I can't foresee any situation where admin intervention would be required.

**Comment by CalumTowers** [comment]
@NFarrington There have been a number of support requests requiring intervention - take a gander at the last month or so.
Not sure if there was an issue with resetting passwords that was then resolved?

**Comment by NFarrington** [comment]
There were a couple of commits in November relating to password reset fixes, 690da415efd4c118ddc10c25ad948fcea7cb5784 and fb6c1537749d187da4b974f85c324c06080e7a30.

At the moment, I can't see any issues. If there are issues with specific people, rough dates and times of the login/reset attempts and details of the issue can then be used to find and resolve it.

Implementing the suggestions in this issue would be counterproductive, since if there is an issue, we need to fix it, rather than encouraging using a workaround and continuing to provide users with a broken process.

If anyone submits a ticket about reset issues, let me know and we can look at this further.
