### ISSUE TITLE
Mysql connection charset to prod_rts database

### ISSUE THREAD

**Issue by NFarrington** [VATSIM-UK/core#572]
In gitlab by @jpfox on Nov 19, 2016, 17:09

When member names are being updated directly by Core connecting into prod_rts.members, the names are being corrupted because UTF-8 data is being sent over a latin1 (ISO-8859-1) connection. (The tables themselves are currently latin1 but due to be changed over to UTF-8 soon, but actually this is immaterial - it will work either way so long as the connection charset is set correctly.)

Regardless of the database/table/column charset, I think the default connection charset is the server charset, which presently is latin1. So what I assume is happening is that no charset is being specified for the RTS database connection, leading to the default being used. (I haven't checked the Core code.)

Therefore, all you need to do is call mysqli_set_charset('utf8mb4') (or something equivalent) when setting up the connection. You can do this now, it won't be affected by the pending switch from latin1 to utf8mb4 at the RTS end (except that after the change is done, the RTS system will have full unicode support instead of a small subset, which affects a few people's names).

**Comment by jpfox** [comment]
(Sorry, my message does not concern the issue but I don't know where to explain it)

My user name on github is jpfox. It seems that someone on your gitlab as same one, but it's not me.

Is it possible to modify your gitlab/github bridge to remove @ before gitlab user name. I receive many notification due to @jpfox and issues seem to be associated with my github profile. It's not very pleasant :-( 

Thank you if you can make such a modification.

**Comment by A-Lawrence** [comment]
Apologies @jpfox - we migrated from GitLab and some old issues had that username in.  You shouldn't receive any future notifications!

**Comment by jpfox** [comment]
many thanks :-)
