### ISSUE TITLE
When feedback is left about me, I should receive an email

### ISSUE THREAD

**Issue by A-Lawrence** [VATSIM-UK/core#605]
_Pending review of consultation feedback._

When somebody leaves feedback about a user, the _target_ user should be sent an email explaining that new feedback has been left.

Related to issue #605.

**Comment by atoff** [comment]
After having discussed internally, we have decided that if community would like this option they will request it. Due to the possibility of abuse, it will not be implemented in the first version of the system. For the moment it will be left up to the individual training teams to approach target users as and when required.
