### ISSUE TITLE
Referees Expire

### ISSUE THREAD

**Issue by CalumTowers** [VATSIM-UK/core#933]
Set an expires_at date for all referees. This should be +7 days from the date that the V/T application was submitted_at by the member.

If a referee fails to reply within 7 days, the application should be cancelled (perhaps create a new status as it doesn't fit into either Withdrawn, Rejected or Expired Automatically).

Emails to referees should be updated to ensure it is clear that they have 7 days.

**Comment by NFarrington** [comment]
It might make more sense to allow the candidate to choose another referee or send a reminder to the current referee, rather than cancelling their application and making them go through the process of submitting another application again.

If, after 3 attempts to get the reference (where the candidate has chosen a new referee or chosen to remind the current one), there is still no reference, the application would then be cancelled to free up the training space.

If a candidate does not choose an option within 7 days of the reference expiring, the application is then cancelled.

**Comment by CalumTowers** [comment]
Agreed. Let's go ahead with that.
